AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  deep-larva-server

  Sample SAM Template for deep-larva-server

Parameters:
  Stage:
    Type: String
    Default: production
    AllowedValues:
      - local
      - production
    Description: Set the stage of the development cycle. Default is production.

Mappings:
  EnvironmentMap:
    local:
      production: false
    production:
      production: true

Globals:
  Function:
    Timeout: 100
    MemorySize: 512
    Runtime: python3.12
    LoggingConfig:
      LogFormat: JSON

Resources:
  DeepLarvaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: deep_larva_function
      Handler: handler.lambda_handler
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: PictureTable
        - DynamoDBCrudPolicy:
            TableName: BoxDetectionTable
        - S3CrudPolicy:
            BucketName: deep-larva-storage
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: PowertoolsDeepLarvaServer
          POWERTOOLS_METRICS_NAMESPACE: Powertools
          LOG_LEVEL: INFO
          ## Environment variables
          LAMBDA_ENV: True
          PRODUCTION: !FindInMap [EnvironmentMap, !Ref Stage, production]
      Events:
        ApiGateway:
          Type: "Api"
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref DeepLarvaApi
      Tags:
        LambdaPowertools: python

  DeepLarvaApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage

  PictureTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PictureTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: deviceId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: IdAndDeviceIdIndex
          KeySchema:
            - AttributeName: id
              KeyType: HASH
            - AttributeName: deviceId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  BoxDetectionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BoxDetectionTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: pictureId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: IdAndPictureIdIndex
          KeySchema:
            - AttributeName: id
              KeyType: HASH
            - AttributeName: pictureId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  DeepLarvaS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: deep-larva-storage
