name: PR Checks

on:
  pull_request:
    branches:
      - development
      - main

jobs:
  tests-and-linting-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12.4"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install -r requirements-dev.txt

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          pylint: true
          pylint_args: "--disable=missing-function-docstring,line-too-long,too-few-public-methods,no-value-for-parameter"

      - name: Run isort
        uses: isort/isort-action@v1
        with:
          configuration: "--profile black --check-only --diff"

      - name: Install testing dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi

      - name: Test with pytest
        run: |
          coverage run -m pytest  -v -s
