name: Deploy to AWS Reusable Actions

on:
  workflow_call:
    inputs:
      SAM_TEMPLATE:
        required: true
        type: string
      STACK_NAME:
        required: true
        type: string
      ARTIFACTS_BUCKET:
        required: true
        type: string
      REGION:
        description: "AWS region to deploy to"
        required: false
        default: "us-east-1"
        type: string
      PARAMETER_OVERRIDES:
        required: false
        type: string
        # prettier-ignore
        default: "Environment=\"production\""
    secrets:
      PIPELINE_EXECUTION_ROLE:
        required: true
      CLOUDFORMATION_EXECUTION_ROLE:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SAM
        uses: aws-actions/setup-sam@v2
        with:
          version: 1.141.0
          use-installer: true

      - name: Assume the AWS role
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-region: ${{ inputs.REGION }}
          role-session-name: gh-session-deployment
          role-to-assume: ${{ secrets.PIPELINE_EXECUTION_ROLE }}

      - name: Build the SAM template
        run: sam build --template ${{ inputs.SAM_TEMPLATE }}

      - name: Deploy the stack to the target account
        shell: bash
        run: |
          sam deploy --stack-name ${{ inputs.STACK_NAME }} \
            --capabilities CAPABILITY_IAM \
            --region ${{ inputs.REGION }} \
            --no-confirm-changeset \
            --s3-bucket ${{ inputs.ARTIFACTS_BUCKET }} \
            --s3-prefix ${{ inputs.STACK_NAME }} \
            --no-fail-on-empty-changeset \
            --role-arn ${{ secrets.CLOUDFORMATION_EXECUTION_ROLE }} \
            ${{ inputs.PARAMETER_OVERRIDES != '' && format('--parameter-overrides {0}', inputs.PARAMETER_OVERRIDES) || '' }}
